import "./globals.scss";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata = {
  title: "COSCUP 2023 x OpenAI 議程搜尋系統",
  // description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-Hant" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
