import './globals.css'

export const metadata = {
  title: 'Coscup 2023 feat. OpenAI',
  // description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
